# Generated by Django 5.1.6 on 2025-02-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='logo',
            field=models.ImageField(null=True, upload_to='artists/'),
        ),
    ]
