# Generated by Django 5.1.6 on 2025-02-25 17:53

import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="publication_time",
            field=models.DateTimeField(
                default=player.models.Track.default_publication_time
            ),
        ),
    ]
