# Generated by Django 5.1.6 on 2025-03-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0003_playlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="slug",
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
    ]
