# Generated by Django 5.1.6 on 2025-02-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_genre_artist_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.genre'),
        ),
    ]
