# Generated by Django 5.1.6 on 2025-02-19 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_alter_artist_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(null=True, upload_to='tracks_logo/')),
                ('mp3', models.FileField(null=True, upload_to='tracks/')),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(default=0, max_length=32)),
                ('is_published', models.BooleanField(choices=[(0, 'НЕОПУБЛИКОВАННЫЙ'), (1, 'ОПУБЛИКОВАННЫЙ')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.genre')),
            ],
            options={
                'ordering': ['-time_created'],
                'indexes': [models.Index(fields=['-time_created'], name='player_trac_time_cr_669e5f_idx')],
            },
        ),
    ]
