# Generated by Django 5.1.6 on 2025-02-19 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='author',
            new_name='main_author',
        ),
        migrations.AddField(
            model_name='track',
            name='featured_authors',
            field=models.ManyToManyField(blank=True, related_name='featured_artists', to='player.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='publication_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
