# Generated by Django 5.1.6 on 2025-02-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_rename_author_track_main_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'НЕОПУБЛИКОВАННЫЙ'), (1, 'ОПУБЛИКОВАННЫЙ')], default=1),
        ),
    ]
