# Generated by Django 5.1.6 on 2025-02-19 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_alter_track_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('publication_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(null=True, upload_to='playlists/')),
                ('is_published', models.BooleanField(choices=[(0, 'НЕОПУБЛИКОВАННЫЙ'), (1, 'ОПУБЛИКОВАННЫЙ')], default=1)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.genre')),
                ('main_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.artist')),
                ('tracks', models.ManyToManyField(blank=True, related_name='albums', to='player.track')),
            ],
            options={
                'ordering': ['-time_created'],
                'indexes': [models.Index(fields=['-time_created'], name='player_albu_time_cr_592dce_idx')],
            },
        ),
    ]
