# Generated by Django 5.1.6 on 2025-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
    ]
