# Generated by Django 5.1.6 on 2025-02-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_album_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='track',
            name='player_trac_time_cr_669e5f_idx',
        ),
        migrations.AddField(
            model_name='track',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['id'], name='player_trac_id_edfca0_idx'),
        ),
    ]
