# Generated by Django 5.1.6 on 2025-02-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_alter_track_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_confirmed',
            field=models.BooleanField(choices=[(0, 'НЕПОДТВЕРЖДЕННЫЙ'), (1, 'ПОДТВЕРЖДЕННЫЙ')], default=1),
        ),
    ]
