# Generated by Django 5.1.6 on 2025-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0011_alter_artist_is_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "Неопубликованный"), (1, "Опубликованный")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="is_confirmed",
            field=models.BooleanField(
                choices=[(0, "Неподтвержденный"), (1, "Подтвержденный")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "Неопубликованный"), (1, "Опубликованный")], default=1
            ),
        ),
    ]
